services:

  pipeline:
    build: .
    container_name: whale-sightings-pipeline
    depends_on:
      - db
    volumes:
      - ./data:/app/data
    networks:
      - whale-network


  db:
    build: ./db
    container_name: whale-sightings-db
    restart: always
    volumes:
      - whale-db:/var/lib/mysql
    networks:
      - whale-network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}

  jupyter:
    build: 
      context: .
      dockerfile: ./notebooks/Dockerfile
    container_name: whale-sightings-jupyter
    ports:
      - "8888:8888"
    depends_on:
      - db
    volumes:
      - ./.env:/home/jovyan/work/.env
      - ./notebooks/visualizations.ipynb:/home/jovyan/work/visualizations.ipynb
    networks:
      - whale-network

networks:
  whale-network:
volumes:
  whale-db: